name: C

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compilar programa
      run: |
        gcc arquivo-ox.c function_validar.c -o arquivo-ox

    - name: Compilar testes
      run: |
        gcc test_arquivo-ox.c function_validar.c -o teste

    - name: Executar testes
      run: |
        ./teste

    - name: Executar programa
      run: |
        ./arquivo-ox tabuleiro.txt O O O X X X O O O

    - name: Mostrar arquivo gerado
      run: |
        cat tabuleiro.txt
